Proc import datafile = "Z:\Assignments\Graded Assignment\Topic 13 - Final Case Study Implementation\telecomfinal.csv" dbms=csv out=finaltel replace;
run;
data finaltel1;
set finaltel;
mean_mou = mou_mean * 1;
inc = income*1;
Mean_totmrc = totmrc_Mean * 1;
Range_Rev = rev_Range * 1;
Range_mou = mou_Range * 1;
changmou = change_mou * 1;
dayseqp = eqpdays * 1;
Mean_ovrmou = ovrmou_Mean * 1;
mou6avg = avg6mou * 1;
qtyavg = avg6qty * 1;
ovrevMean = ovrrev_Mean * 1;
rvMean = rev_Mean * 1;
areaa = area + 0;
refrbnew = refurb_new + 0;
prizmone = prizm_social_one + 0;
hndwbcap = hnd_webcap + 0;
maritaal = marital + 0;	
ethnicc = ethnic + 0;	
age11 = age1 * 1;	
age22 = age2 * 1;
model = models * 1;	
hndpr = hnd_price * 1;
forgntl = forgntvl * 1;	
dwlltyp = dwlltype + 0;	
dwllsiz = dwllsize + 0;
mailord = mailordr + 0;	
occu = occu1 + 0;
mtrcycl = mtrcycle	+ 0;
numbcar = numbcars + 0;
retday = retdays + 0;
truckk = truck * 1;
wrkwomann = wrkwoman + 0;	
Meanroam = roam_Mean * 1;
slflg = solflag + 0;
proptyp = proptype + 0;	
mlresp = mailresp + 0;	
cartyp = cartype + 0;
carbuy = car_buy + 0;	
childrn = children + 0;
csaa = csa + 0;
Meanda	= da_Mean * 1;	
Rangeda = da_Range * 1; 
Meandatovr = datovr_Mean * 1;	
Rangedatovr = datovr_Range * 1;
typediv = div_type + 0;
proc contents data= finaltel1;
run;
proc means data = finaltel1 n nmiss mean std min max mode median;
run;
proc freq data = finaltel1;
table churn;
run;
proc means mean data=finaltel1;
class CRCLSCOD;
var inc;
output out = finalprep (drop = _type_ _freq_ _stat_);
run;
proc sort data=finaltel1;
by CRCLSCOD;
run;
DATA finaltel2;
merge finaltel1 (in=a) finalprep (in=b);
by CRCLSCOD;
if A and B;
run;
data finaltel2;
set finaltel2;
if inc LE 4.9 then income_bkt = 1;
else if inc LE 6 then income_bkt = 2;
else if inc LE 7 then income_bkt = 3;
else income_bkt = 4;
if callwait_mean LE 0 then callwait_bkt = 1;
else if callwait_mean le 0.334 then callwait_bkt = 2;
else if callwait_mean le 1.67 then callwait_bkt = 3;
else callwait_bkt = 4;
if Meanroam > 0 then roam_ind = 1;
else roam_ind = 0;
if drop_blk_mean LE 1.67 then drop_blk_bkt = 1;
else if drop_blk_mean LE 5.34 then drop_blk_bkt = 2;
else if drop_blk_mean LE 12.67 then drop_blk_bkt = 3;
else drop_blk_mean = 0;
if 	PLCD_VCE_MEAN le 40.67 then PLCD_VCE_bkt = 1;
else if PLCD_VCE_MEAN LE 103.67 then PLCD_VCE_bkt = 2;
else if PLCD_VCE_MEAN LE 202.67 then PLCD_VCE_bkt = 3;
else PLCD_VCE_bkt = 4;
If INDEX(areaa,'DALLAS') > 0 OR INDEX(areaa,'YORK') > 0 OR INDEX(areaa,'HOUSTON') > 0 OR INDEX(areaa,'ANGELES') > 0 OR INDEX(areaa,'CHICAGO') > 0 OR INDEX(areaa,'PHILA') THEN areaa_iscity = 1;
else if INDEX(areaa, 'ROCKY') > 0 then areaa_ismount =1;
else areaa_isrural = 1;
areaa_iscity = 0;
areaa_ismount = 0;
areaa_isrural = 0;
if asl_flag = 'Y' then aslflag = 1;
else aslflag = 0;
If ethnicc = '0' then isasian = 1;
else isasian = 0;
if ethnicc = 'H' then isHisp = 1;
else isHisp = 0;
if ethnicc = 'G' then isgerman = 1;
else isgerman = 0;
if ethnicc = 'F' then isfrench = 1;
else isfrench = 0;
if ethnicc = 'Z' then isafro = 1;
else isafro = 0;
If wrkwomann = 'Y' then woman_ind = 1;
woman_ind = 0;
if refurbnew = 'N' then hnd_new = 1;
else hnd_new = 0;
if Carbuy = 'New' then car_new = 1;
else car_new = 0;
if CARTYP = 'E' then car_reg = 1;
else car_reg = 0;
if CARTYP = 'F' then car_up = 1;
else car_up = 0;
if childrn = 'N' then no_child = 1;
else no_child = 0;
if STRIP(crclscod) = 'A' then credclas_a = 1;
if STRIP(crclscod) = 'AA' then credclas_a = 1;
else credclas_a = 1;
if STRIP(dwllsiz) = 'A' then dwell_a = 1;
else dwell_a = 0;
if STRIP(hndwebcap) = 'WCMB' then webcap_ind = 1;
else webcap_ind = 0;
if model = 1 then one_model = 1;
else one_model = 0;
if STRIP(retday) ='NA' then retcall_ind = 0;
else retcall_ind = 1;
if dayseqp LE 202 then eqp_age = 1;
else if dayseqp LE 326 then eqp_age = 2;
else if dayseqp LE 512 then eqp_age = 3;
else eqp_age = 4;
if months LE 11 then rship_age = 1;
else if months LE 16 then rship_age = 2;
else if months LE 24 then rship_age = 3;
else rship_age = 4;
if avgmou LE 176.67 then avgmou_bkt = 1;
else if avgmou LE 362.5 then avgmou_bkt = 2;
else if avgmou LE 660.9 then avgmou_bkt = 3;
else avgmou_bkt = 4;
if TOTCALLS LE 860 then totcalls_bkt = 1;
else if TOTCALLS LE 1796 then totcalls_bkt = 2;
else if TOTCALLS LE 3508 then totcalls_bkt = 3;
else totcalls_bkt = 4;
if TOTREV LE 860 then totrev_bkt = 1;
else if TOTREV LE 1796 then totrev_bkt = 2;
else if TOTREV LE 3508 then totrev_bkt = 3;
else totrev_bkt = 4;
run;
proc means data = finaltel2 n nmiss;
run;
proc surveyselect data = finaltel2
method = srs
out = finalsample1
samprate = 0.5 
outall;
run;
data training validatefinal;
set finalsample1;
if selected = 0 then output training;
else if selected = 1 then output validatefinal;
run;
proc logistic data = training descending;
model churn = AVGMOU AVG3MOU PLCD_VCE_bkt drop_blk_bkt iwylis_vce_mean changmou drop_vce_range drop_vce_mean
areaa_ismount aslflag Mean_totmrc age11 isasian ishisp isafro hndpr Mean_ovrmou Meanroam hnd_new no_child
webcap_ind model actvsubs uniqsubs retcall_ind rship_age eqp_age totcalls_bkt income_bkt callwait_bkt roam_ind
areaa_iscity areaa_isrural mou6avg woman_ind car_new car_reg car_up credclas_a dwell_a one_model ovrevmean / selection = forward ctable lackfit;
run;
proc logistic data = validatefinal descending;
model churn = AVGMOU AVG3MOU plcd_vce_bkt drop_blk_bkt iwylis_vce_mean changmou drop_vce_range DROP_VCE_MEAN
areaa_ismount aslflag Mean_totmrc age11 isasian ishisp isafro hndpr mean_ovrmou Meanroam hnd_new no_child
webcap_ind model actvsubs uniqsubs retcall_ind rship_age eqp_age totcalls_bkt income_bkt callwait_bkt roam_ind
areaa_iscity areaa_isrural mou6avg woman_ind car_new car_reg car_up credclas_a dwell_a one_model ovrevmean / selection = forward ctable lackfit;
run;
proc logistic data = finaltel2 descending outmodel = dmm;
model churn = AVGMOU AVG3MOU PLCD_VCE_bkt drop_blk_bkt changmou drop_vce_range DROP_VCE_MEAN
areaa_ismount aslflag Mean_totmrc age11 isasian ishisp isafro hndpr mean_ovrmou Meanroam hnd_new no_child
webcap_ind actvsubs uniqsubs retcall_ind rship_age eqp_age totcalls_bkt one_model ovrevmean / ctable lackfit;
score out = dmp;
run;
proc rank data = dmp out = finaldcee groups = 10 ties = mean;
var p_1;
ranks decile;
run;
proc sort data = finaldcee;
by descending p_1;
run;
proc export data = finaldcee
outfile = 'Y:\WINDOWS\system\Jig12752\FINAL CASE STUDY\Gain.xlsx'
dbms = excel;
run;
data testacc;
set dmp;
if f_churn = 0 and i_churn = 0 then out = "True Negative";
else if f_churn = 1 and i_churn = 1 then out = "True Positive";
else if f_churn = 0 and i_churn = 1 then out = "False Positive";
else if f_churn = 1 and i_churn = 0 then out = "False Negative";
run;
Proc freq;
tables out;
run;
ods select quantiles;
proc univariate data = finaltel1;
var opk_dat_mean blck_dat_MEAN datovr_mean datovr_Range drop_dat_mean;
run;
proc univariate data=finaltel1 noprint;
 var opk_dat_mean blck_dat_MEAN datovr_mean datovr_Range drop_dat_mean;
 output out=pctl pctlpts=20 50 90 pctlpre=p;
run;


